spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AbsoluteCinema
    username: postgres
    password: 1a2b3c4d
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false